@localhost = http://localhost:3333


#################################################### USERS ########################################


### Cria um usuário
POST {{localhost}}/auth/register
content-Type: application/json

{
  "name": "diego",
  "email": "diegolimareis21@gmail.com",
  "password":"NovaSenha123"
}


### Confirma o email do usuário
GET {{localhost}}/email/confirm?token=bfa1e355-4ffd-4250-beaf-e631e75c0678


### Envia um email para recuperar sua senha
POST {{localhost}}/password/forgot
content-Type: application/json

{
  "email": "diegolimareis21@gmail.com"
}

### Atualizar a senha
PATCH  {{localhost}}/password/reset?token=cd8f9dfd-f899-418c-b1c8-a5a999a9bb2e
content-Type: application/json

{
  "password": "NovaSenha123"
}

### Faz Autenticação de um usuário
POST {{localhost}}/auth/login
content-Type: application/json

{
  "email": "diegolimareis21@gmail.com",
  "password":"P@ssw0rd!2024"
}

#################################################### VEHICLES ########################################

### Cadastra um veículo
POST {{localhost}}/vehicles
content-Type: application/json

{
  "title": "Crossover Moderno",
  "description": "Design moderno e inovador, perfeito para todos os terrenos.",
  "price": 50000,
  "model": "CX-5",
  "brand": "mazda",
  "year": 2020,
  "status": "AVAILABLE"
}

### Lista todos os veículos
GET  {{localhost}}/vehicles



### Filtra os veículo por status
GET {{localhost}}/vehicles/search/status=SOLD


### Busca veículo pelo modelo
GET {{localhost}}/vehicles?model=mazda