@localhost = http://localhost:3333


#################################################### USER ########################################


### Cria um usuário
POST {{localhost}}/auth/register
content-Type: application/json

{
  "name": "diego",
  "email": "diegolimareis21@gmail.com",
  "password":"P@ssw0rd!2024"
}


### Confirma o email do usuário
GET {{localhost}}/email/confirm?token=bfa1e355-4ffd-4250-beaf-e631e75c0678


### Faz Autenticação de um usuário
POST {{localhost}}/auth/login
content-Type: application/json

{
  "email": "diegolimareis21@gmail.com",
  "password":"P@ssw0rd!2024"
}
